### ISSUE TITLE
Out of memory error on video messages and ship menu animations.

### ISSUE THREAD

**Issue by mokee9** [akarnokd/open-ig#1026]
I'm getting these java heap-space errors on every game. Strangely it only seems to occur on my PC because it works fine on my laptop.
i've tried changing the available memory to 1024mb.
---------
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_241
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, x86, 10.0
   Game version: 0.95.212
   Command line: [-memonce, -en]
   Available memory: 2 MB
   Maximum memory: 494 MB
   Parallelism: 8
   Language: en
   Date and time: 2020-02-14T04:48:05.253Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
C:\Users\Matt\Desktop\OpenIG\save\default\save-2020-02-14-14-48-05-271.xml.gz
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at sun.awt.image.SunVolatileImage.getBackupImage(Unknown Source)
	at sun.awt.image.VolatileSurfaceManager.getBackupSurface(Unknown Source)
	at sun.awt.image.VolatileSurfaceManager.restoreContents(Unknown Source)
	at sun.java2d.d3d.D3DVolatileSurfaceManager.restoreContents(Unknown Source)
	at sun.java2d.SurfaceData.restoreContents(Unknown Source)
	at sun.java2d.d3d.D3DSurfaceData.getReplacement(Unknown Source)
	at sun.java2d.SunGraphics2D.revalidateAll(Unknown Source)
	at sun.java2d.SunGraphics2D.fillRect(Unknown Source)
	at hu.openig.screen.items.BridgeScreen.paintLabel(BridgeScreen.java:897)
	at hu.openig.screen.items.BridgeScreen.draw(BridgeScreen.java:799)
	at hu.openig.GameWindow$ScreenRenderer.paint(GameWindow.java:238)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)

Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at sun.awt.image.SunVolatileImage.getBackupImage(Unknown Source)
	at sun.awt.image.VolatileSurfaceManager.getBackupSurface(Unknown Source)
	at sun.awt.image.VolatileSurfaceManager.validate(Unknown Source)
	at sun.awt.image.SunVolatileImage.validate(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Movie Audio" java.lang.OutOfMemoryError: Java heap space

**Comment by akarnokd** [comment]
The error indicates you have set it only to 512 MB. Go into the launcher's options and change the memory amount there.

**Comment by mokee9** [comment]
> 
> 
> The error indicates you have set it only to 512 MB. Go into the launcher's options and change the memory amount there.

It has been changed in the launcher already, i set it to 1024mb, but it doesn't seem to be communicating that to java.

it seems to be changing its maximum memory because other errors are different. 
494mb, 512mb, 455mb seem to be the most common. But nothing more than 512.


You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_241
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.212
   Command line: [-memonce, -en, -continue]
   Available memory: 57 MB
   Maximum memory: 455 MB
   Parallelism: 8
   Language: en
   Date and time: 2020-02-14T12:19:56.192Z

**Comment by akarnokd** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/1269832/74533192-4a7e3b80-4f31-11ea-8d29-a83e1f0d4d70.png)

![image](https://user-images.githubusercontent.com/1269832/74533250-6e418180-4f31-11ea-8a3a-f81f36158f4c.png)

**Comment by mokee9** [comment]
Where did you get that java properties window?

**Comment by akarnokd** [comment]
![image](https://user-images.githubusercontent.com/1269832/74537401-4efb2200-4f3a-11ea-96df-680ab0b462b5.png)

**Comment by mokee9** [comment]
Not that one, this one. 

https://user-images.githubusercontent.com/1269832/74533250-6e418180-4f31-11ea-8a3a-f81f36158f4c.png

Well i've tried everything, adding Xmx1024m to the JVM also didn't help. I guess i'll just play it on my laptop.

**Comment by akarnokd** [comment]
That's a tool called [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).

As a last resort, you can go into the game's folder, open a command prompt and run the following manually:

`java -Xmx1024M -jar open-ig-0.95.212.jar -memonce -en`

**Comment by mokee9** [comment]
No luck. It ran the game but the same errors. But command prompt showed this as a log which is interesting...

C:\Users\Admin\OpenIG>java -Xmx1024M -jar open-ig-0.95.212.jar -memonce -en
Picked up _JAVA_OPTIONS: -Xmx512M
java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferInt.<init>(Unknown Source)
        at java.awt.image.Raster.createPackedRaster(Unknown Source)
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at hu.openig.screen.TechnologyVideoRenderer.prepare(TechnologyVideoRenderer.java:126)
        at hu.openig.screen.TechnologyVideoRenderer$1.run(TechnologyVideoRenderer.java:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

java.lang.IndexOutOfBoundsException: Index: 56, Size: 56
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at hu.openig.screen.TechnologyVideoRenderer$3$1.invoke(TechnologyVideoRenderer.java:166)
        at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:866)
        at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
---

"Picked up _JAVA_OPTIONS: -Xmx512M"  Does this mean a Java setting is overriding it?

**Comment by akarnokd** [comment]
Yes, looks like something has set that environmental option and thus overrides the setting. Are you running other java-based applications on your system?

**Comment by mokee9** [comment]
None that are running from what i can tell, i have also reinstalled java like a dozen times.

**Comment by akarnokd** [comment]
Then it should be safe to remove it from Windows' environmental variables.

**Comment by mokee9** [comment]
Ha.. There it was Windows' environmental variables. -Xms512m.

And That's fixed it, thanks for the help :)
Another program must have put that variable in there at some point.
