### ISSUE TITLE
critical bug regarding open-ig-launcher.jar which prevents me from playing the game

### ISSUE THREAD

**Issue by Alienigene** [akarnokd/open-ig#1030]
I was born in People's Republic of China and I and still in China, behind the infamous Great Firewall of China, GitHub contents are hosted on s3.amazonaws.com, which is blocked/slowed, rendering downloading anything from GitHub nearly impossible because of very slow speed and downloads always fail near completion due to broken connection, unless you know the tricks to bypass GFW.

I used to edit hosts file to access blocked websites like en.wikipedia.org and www.deviantart.com et cetera, websites which are blocked by dns poisoning, but this method does not allow me to access websites like www.google.com and www.quora.com which
are blocked using much more advanced techniques, and to counter these techniques I need an encrypted connection to a proxy server.

I am currently using shadowsockr to visit unblocked internet, which in my experience is the only reliable method to bypass GFW,
all other VPN/Proxies either don't work at all or are unstable. But it has a problem, it does not proxy all traffics. All web browsers automatically use the proxy without configuration, most downloaders can be configured to use the proxy, but all console programs and many other programs can't be proxied.

I am using Windows 10 64-bit latest edition, I have installed Java Runtime Environment 8 Update 251 amd64 and x86, Java SE Development Kit 14.0.1 amd64, and set Java environment variables to jdk.

Obiviously open-ig-launcher.jar isn't full offline installer, it requires connection to raw.githubusercontent.com to download the game files, which seems to be blocked.

Every time I try to start the game using open-ig-launcher.jar an error window pops up
Error during data download:  java.util.concurrent.ExecutionException: java.net.UnknownHostException: raw.githubusercontent.com

And downloading by this program is impossible.

Too bad there isn't a complete offline installer or a binary release zip file, this game seems intriguing. And too interesting for me to give up so easily. So I browsed the project files, I downloaded the following files in ./install/: open-ig-0.95.214.jar, open-ig-audio-en-20120623A.zip, open-ig-audio-generic-20121121A.zip, open-ig-images-20140910a.zip, open-ig-upgrade-20200222a2.zip, open-ig-video-01.zip to open-ig-video-10-0.8.zip and open-ig-video-en-20120423A.zip, and downloaded all the files in the root folder that aren't "Removed branch directories", I then put all the stuff in a single directory, extracted all zip files and renamed *audio* folder to audio, *video* folders to video *images* folder to images, *update* to data, merging all subfolders, then deleted the zip files.

So I think I have all the game files in a proper folder structure. And then I launched open-ig-launcher.jar, hoping to play the game, but to my surprise and dismay, it doesn't recognize all the local files at all, treating all these stuff as non-existent, despite the fact that they are in the very same folder! It still tries to download all those stuff from raw.githubusercontent.com, and that website is blocked, it can't download the stuff I have already downloaded using a proxy, and it doesn't recognize what I have downloaded. So it really impossible for me to play this game, can anyone help me? Please!

**Comment by akarnokd** [comment]
You don't have to extract the zips. But keep them as they are:

![image](https://user-images.githubusercontent.com/1269832/86510819-94d65b00-bdf3-11ea-8542-12cbd1934759.png)

Then simply launch `open-ig-0.95.214.jar` without the launcher.

Github doesn't allow files bigger than 200MB so I can't host big files here.

**Comment by Alienigene** [comment]
I redownloaded the 15 zips I downloaded earlier, requiring me to click twice for each, I clicked 30 times in total. Then I decompressed every file, because there is a non-zero chance compressed files downloaded from GitHub and SourceForge may be corrupt, and there are no hash values provided. After I was sure the files aren't corrupted, I did exactly as you said, however the problem persists, the crash message will be pasted below. P.S. Would you like to release this project to SourceForge as well?

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 14.0.1
   Java vendor: Oracle Corporation (https://java.oracle.com/)
   Java class version: 58.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.45
   Command line: []
   Available memory: 38 MB
   Maximum memory: 950 MB
   Parallelism: 4
   Language: en
   Date and time: 2020-07-04T11:20:30.196Z
----
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at hu.openig.launcher.Launcher.selectLanguagesToInstall(Launcher.java:2468)
	at hu.openig.launcher.Launcher$25.actionPerformed(Launcher.java:747)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Alienigene** [comment]
Correction: My RAM is DDR4 4GB, there is no dedictated graphics card in my machine, so there is an Intel integrated one, after subtracting shared memory, total available memory is 3798 MB.

**Comment by Alienigene** [comment]
Nevermind, I have solved this problem now, I have only download en and generic, because I only excel in English, to download other localizations would be a waste of HDD space. The game couldn't launch because it couldn't find other languages, which I haven't downloaded. Specifically, this game couldn't launch because it was set to launch with hu, after I changed hu in Notepad++ to en in open-ig-config.xml, problem solved. I downloaded the file from GitHub directly and didn't view it, I thought it would be set to en by default......

**Comment by akarnokd** [comment]
> I thought it would be set to en by default

GitHub hosts the development files and I developed the game set to Hungarian by default. If you were able to go through the launcher, you would have had the option to select the language and install what's necessary.

Since you are in a special location, you'll have to do a lot of manual workarounds.

> Would you like to release this project to SourceForge as well?

No.

**Comment by Alienigene** [comment]
Actually I think this whole proccess was quite fun, quite intriguing, and I somehow enjoyed it, like solving a puzzle. Maybe it just me, maybe I am too clever, but I just like puzzles, secrets, mysteries, that is why I like Windows, full of puzzles, Control Panel, Command Prompt, Powershell, Registry Editor, Group Policy Editor, Task Manager, Resource Monitor; Visual C++ Redistributables, DirectX, .NET Framework, drivers, hosts... It's quite challenging, funny and entertaining, to solve this thing and that, makes me feel like I have achieved something many others haven't achieved. But most people just don't want to pay the time to learn new things, they wouldn't have done what I have done if they can't use the launcher, so many people wouldn't be able to play this game if they can't use the launcher.  I really do think this game to be a good game, but your audience would be heavily dimished...... In all I think this process funny, but I could be much simpler, if only the main page of the project is more informational.

**Comment by akarnokd** [comment]
I'm glad it worked for you at the end.

If you think many people would be interested of this game behind the GFW, I recommend setting up a mirror behind it with all the necessary information for the non-launcher installation.
