### ISSUE TITLE
kolonozálo, darabos mozgás

### ISSUE THREAD

**Issue by FaLiar** [akarnokd/open-ig#1073]
ez a problémát már irtam egyszer, elvileg valamit javitottál is. 

a kolonizáló hajó mozgása darabos, megáll elindul, megáll elindul, (4szeres sebezsségen //  20 min / lépés)

nem mindig van igy,...

lehet erre irtad hogy adjak neki több memoriát?

itt a save
https://drive.google.com/drive/folders/19LBhsqekD4CkT9bOpf3E3_0dL3uEWvcA?usp=share_link

még hibaüzit is kaptam késöbb

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_361
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 7, x86, 6.1
   Game version: 0.95.234
   Command line: [-memonce, -hu, -continue]
   Available memory: 329 MB
   Maximum memory: 989 MB
   Parallelism: 8
   Language: hu
   Date and time: 2023-02-01T20:25:46.497Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
E:\IG1\save\default\save-2023-02-01-21-25-46-522.xml.gz
java.lang.NullPointerException
	at hu.openig.mechanics.ColonizationPlanner.colonizeWithExistingFleets(ColonizationPlanner.java:125)
	at hu.openig.mechanics.ColonizationPlanner.planExplicitConquest(ColonizationPlanner.java:177)
	at hu.openig.mechanics.ColonizationPlanner.plan(ColonizationPlanner.java:64)
	at hu.openig.mechanics.Planner.run(Planner.java:232)
	at hu.openig.mechanics.AIUser.manage(AIUser.java:131)
	at hu.openig.screen.CommonResources.runAIAsync(CommonResources.java:709)
	at hu.openig.screen.CommonResources$19.run(CommonResources.java:679)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by FaLiar** [comment]
crash save is mellékelve, ez már java 19en van

**Comment by akarnokd** [comment]
Nézem. Jól beletenyereltél. 😅

**Comment by akarnokd** [comment]
Javítottam.

Részben sikerült belefutnod egy pár évtizede meglévő bugba...

**Comment by FaLiar** [comment]
ha az ember igyekszik :)
