### ISSUE TITLE
Gamebug

### ISSUE THREAD

**Issue by sershil1** [akarnokd/open-ig#1114]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_391
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 11, amd64, 10.0
   Game version: 0.95.242
   Command line: [-memonce, -en]
   Available memory: 95 MB
   Maximum memory: 740 MB
   Parallelism: 20
   Language: en
   Date and time: 2024-01-13T07:36:24.980Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
C:\Users\sersh\Downloads\Open-IG-0.95.X\save\default\save-2024-01-13-10-36-25-072.xml.gz
Exception in thread "TimerQueue" java.lang.OutOfMemoryError: Java heap space

java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.locks.ReentrantLock$Sync.newCondition(Unknown Source)
	at java.util.concurrent.locks.ReentrantLock.newCondition(Unknown Source)
	at javax.swing.TimerQueue.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: Java heap space
	at java.lang.StringBuilder.toString(Unknown Source)
	at java.util.ResourceBundle$Control.toBundleName(Unknown Source)
	at sun.util.resources.LocaleData$LocaleDataResourceBundleControl.toBundleName(Unknown Source)
	at java.util.ResourceBundle$Control.newBundle(Unknown Source)
	at java.util.ResourceBundle.loadBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)
	at java.util.ResourceBundle.findBundle(Unknown Source)
	at java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.util.ResourceBundle.getBundle(Unknown Source)
	at sun.util.resources.LocaleData$1.run(Unknown Source)
	at sun.util.resources.LocaleData$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.util.resources.LocaleData.getBundle(Unknown Source)
	at sun.util.resources.LocaleData.getNumberFormatData(Unknown Source)
	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(Unknown Source)
	at java.text.DecimalFormatSymbols.initialize(Unknown Source)
	at java.text.DecimalFormatSymbols.<init>(Unknown Source)
	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(Unknown Source)
	at java.text.DecimalFormatSymbols.getInstance(Unknown Source)
	at java.util.Formatter.getZero(Unknown Source)
	at java.util.Formatter.<init>(Unknown Source)
	at java.util.Formatter.<init>(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at hu.openig.utils.XElement.toStringRep(XElement.java:554)
	at hu.openig.utils.XElement.toStringRep(XElement.java:548)
	at hu.openig.utils.XElement.toStringRep(XElement.java:548)
	at hu.openig.utils.XElement.save(XElement.java:657)
	at hu.openig.utils.XElement.save(XElement.java:643)
	at hu.openig.GameWindow.save(GameWindow.java:1353)
	at hu.openig.GameWindow$10.call(GameWindow.java:1317)
	at hu.openig.GameWindow$10.call(GameWindow.java:1)
	at java.util.concurrent.FutureTask.run(Unknown Source)

**Comment by akarnokd** [comment]
In the Launcher, go to Other Options > Run Settings and specify the memory to be 1024

![image](https://github.com/akarnokd/open-ig/assets/1269832/a5310f5e-6523-4108-bd68-471fa74f122c)

![image](https://github.com/akarnokd/open-ig/assets/1269832/017ab8ba-db32-4f2b-baca-cf18ea615638)
