### ISSUE TITLE
Crash At level 5 when saved

### ISSUE THREAD

**Issue by MK-coder-bit** [akarnokd/open-ig#1149]
Hi! This is the error msg i received when crashed at level 5 cant save. HELP?
![Uploading IG Crash Save.jpg…]()

**Comment by akarnokd** [comment]
Could you please reupload the crash image?

**Comment by MK-coder-bit** [comment]
Yes this is the error msg~ then just hang there~ 😭😭MK Sent from my iPhoneOn 7 Jun 2024, at 9:57 PM, David Karnok ***@***.***> wrote:﻿
Could you please reupload the crash image?

**Comment by MK-coder-bit** [comment]
![IG Crash Save](https://github.com/akarnokd/open-ig/assets/172049177/a99385c9-2ac1-49f8-a6e5-aecd668eb0fc)

**Comment by MK-coder-bit** [comment]
![Crash Save](https://github.com/akarnokd/open-ig/assets/172049177/bd938b5c-5612-40b6-a4bc-fafc1d407552)

**Comment by MK-coder-bit** [comment]
cant save, it will just hang~

**Comment by akarnokd** [comment]
In the Launcher, open Run Settings:

![image](https://github.com/akarnokd/open-ig/assets/1269832/3433aabe-1ade-4542-8d0d-cfb054c7be75)

And set memory to `1024` or higher.

![image](https://github.com/akarnokd/open-ig/assets/1269832/d652b349-0524-4a98-8341-b1e3fb07c8f1)

**Comment by MK-coder-bit** [comment]
Awesome! it was good for a while, i can save then suddently everything slow & hang again? 2nd error 
![2nd Error](https://github.com/akarnokd/open-ig/assets/172049177/9ddf8ccb-c378-4fe5-9003-5a246725bf0e)
msg

**Comment by akarnokd** [comment]
Could you copy-paste the entire text, not just the screenshot?

You probably have a currupted save. Try one of the autosaves.

**Comment by MK-coder-bit** [comment]
Here you go! auto saves cant load i can load others

**Comment by MK-coder-bit** [comment]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_361
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.247
   Command line: [-memonce, -en]
   Available memory: 155 MB
   Maximum memory: 910 MB
   Parallelism: 12
   Language: en
   Date and time: 2024-06-07T16:02:58.495Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
javax.xml.stream.XMLStreamException: java.io.EOFException
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:327)
	at hu.openig.screen.items.LoadSaveScreen.findSaves(LoadSaveScreen.java:2237)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:744)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:323)
	... 9 more

javax.xml.stream.XMLStreamException: java.io.EOFException
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:327)
	at hu.openig.screen.items.LoadSaveScreen.findSaves(LoadSaveScreen.java:2237)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:744)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:323)
	... 9 more

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.LinkedHashMap.newNode(Unknown Source)
	at java.util.HashMap.putVal(Unknown Source)
	at java.util.HashMap.put(Unknown Source)
	at hu.openig.utils.XElement.parseXML(XElement.java:379)
	at hu.openig.utils.XElement.parseXML(XElement.java:304)
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:324)
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:313)
	at hu.openig.GameWindow$13.run(GameWindow.java:1585)
	at java.lang.Thread.run(Unknown Source)

javax.xml.stream.XMLStreamException: java.io.EOFException
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:327)
	at hu.openig.screen.items.LoadSaveScreen.findSaves(LoadSaveScreen.java:2237)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:744)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:323)
	... 9 more

Exception in thread "TimerQueue" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.concurrent.locks.ReentrantLock$Sync.newCondition(Unknown Source)
	at java.util.concurrent.locks.ReentrantLock.newCondition(Unknown Source)
	at javax.swing.TimerQueue.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: GC overhead limit exceeded

javax.xml.stream.XMLStreamException: java.io.EOFException
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:327)
	at hu.openig.screen.items.LoadSaveScreen.findSaves(LoadSaveScreen.java:2237)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:744)
	at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at java.util.zip.GZIPInputStream.<init>(Unknown Source)
	at hu.openig.utils.XElement.parseXMLGZ(XElement.java:323)
	... 9 more

**Comment by MK-coder-bit** [comment]
And also in my Alien diplomacy only have one alien, but i already explored other aliens area, arent they be available to me for diplomacy? ^O^
![Alien Diplomacy](https://github.com/akarnokd/open-ig/assets/172049177/27697456-0cc6-467c-9fca-b034374f494f)

**Comment by akarnokd** [comment]
Could you post your save?

**Comment by akarnokd** [comment]
Also please delete any save that has 0 cr, those are the corrupted ones.

**Comment by MK-coder-bit** [comment]
This is my save so delete  which one?
![MK Save](https://github.com/akarnokd/open-ig/assets/172049177/349543d6-8aff-4f35-a0f7-d00c8475cdfe)

**Comment by MK-coder-bit** [comment]
When i load Universe & Universe 1, my ships movements are slowed & not fast , then the error msg~

**Comment by akarnokd** [comment]
Delete these:

![image](https://github.com/akarnokd/open-ig/assets/1269832/bdaaa7ca-487b-4c16-bb33-590d28275ebe)

Then just zip up your `save` folder and drag-and-drop into here.

**Comment by MK-coder-bit** [comment]
Sure here is the save zip!
[Uploading save.zip…]()

**Comment by akarnokd** [comment]
Please reupload it and wait until it finishes before clicking comment.

**Comment by MK-coder-bit** [comment]
[save.zip](https://github.com/user-attachments/files/15742691/save.zip)

**Comment by akarnokd** [comment]
@hemoridos Something is not right with the `Universe 1` save. It keeps rediscoverying all races ever secondy. Can you look into it?

![image](https://github.com/akarnokd/open-ig/assets/1269832/61eada31-00b3-46b0-9e3f-db20ee5e6f80)

**Comment by MK-coder-bit** [comment]
yeah man,  that why both my save files my ships movement are slow man, are they corrupted too? haiz
and also since i discovered all these aliens, why are they not in my diplomacy? ;(

**Comment by MK-coder-bit** [comment]
so now which file or autosave file can i load? lol

**Comment by MK-coder-bit** [comment]
my recent save U1 my ships are moving fast speed but the aliens i discovered is not appearing on my diplomacy to interact~
[save-1.zip](https://github.com/user-attachments/files/15742923/save-1.zip)

**Comment by MK-coder-bit** [comment]
Yes last year when I played, it was working so well! Not sure what happen today , it was going so well until I reached the last stage level 5, this crash save & slow movement & error happen, anyway just keep me updated? Thank you so much for the effort! Gtg zzz now, brb tml! MKSent from my iPhoneOn 8 Jun 2024, at 1:17 AM, David Karnok ***@***.***> wrote:﻿
We are looking into your issue. Not sure yet what's wrong exactly.

**Comment by akarnokd** [comment]
Found the issue. Expect a game update shortly.

**Comment by akarnokd** [comment]
Fixed via **0.95.248**. Please update your game.

**Comment by hemoridos** [comment]
Just got the chance read this, Thanks for the fix and sorry for the early release work.

**Comment by MK-coder-bit** [comment]
Hi! I have updated the game, it is better till the same problem arises when saved, it hang on me with the error msg~ Help?


Error msg as below

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
Java version: 1.8.0_361
Java vendor: Oracle Corporation (http://java.oracle.com/)
Java class version: 52.0
Operating system: Windows 10, amd64, 10.0
Game version: 0.95.248
Command line: [-memonce, -en]
Available memory: 174 MB
Maximum memory: 910 MB
Parallelism: 12
Language: en
Date and time: 2024-06-07T23:33:47.622Z

A crash save may have been created. Please attach it in the issue report (zipped).
javax.xml.stream.XMLStreamException: java.io.EOFException
at hu.openig.utils.XElement.parseXMLGZ(XElement.java:327)
at hu.openig.screen.items.LoadSaveScreen.findSaves(LoadSaveScreen.java:2237)
at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:744)
at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:1)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
at java.util.zip.GZIPInputStream.(Unknown Source)
at java.util.zip.GZIPInputStream.(Unknown Source)
at hu.openig.utils.XElement.parseXMLGZ(XElement.java:323)
... 9 more

javax.xml.stream.XMLStreamException: java.io.EOFException
at hu.openig.utils.XElement.parseXMLGZ(XElement.java:327)
at hu.openig.screen.items.LoadSaveScreen.findSaves(LoadSaveScreen.java:2237)
at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:744)
at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:1)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
at java.util.zip.GZIPInputStream.(Unknown Source)
at java.util.zip.GZIPInputStream.(Unknown Source)
at hu.openig.utils.XElement.parseXMLGZ(XElement.java:323)
... 9 more

javax.xml.stream.XMLStreamException: java.io.EOFException
at hu.openig.utils.XElement.parseXMLGZ(XElement.java:327)
at hu.openig.screen.items.LoadSaveScreen.findSaves(LoadSaveScreen.java:2237)
at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:744)
at hu.openig.screen.items.LoadSaveScreen$16.doInBackground(LoadSaveScreen.java:1)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
at java.util.zip.GZIPInputStream.readUByte(Unknown Source)
at java.util.zip.GZIPInputStream.readUShort(Unknown Source)
at java.util.zip.GZIPInputStream.readHeader(Unknown Source)
at java.util.zip.GZIPInputStream.(Unknown Source)
at java.util.zip.GZIPInputStream.(Unknown Source)
at hu.openig.utils.XElement.parseXMLGZ(XElement.java:323)
... 9 more


MK


    On Saturday, 8 June 2024 at 06:15:09 am SGT, Zoltan ***@***.***> wrote:  
 
 


Just got the chance read this, Thanks for the fix and sorry for the early release work.
