### ISSUE TITLE
Game suddenly becomes slow

### ISSUE THREAD

**Issue by Scelletor** [akarnokd/open-ig#1159]
Hi everyone I think it's great that you are still working on this project but I have to say that I only have bugs with this version and have to start new ones every 5 minutes because the game suddenly runs in slow motion

**Comment by Scelletor** [comment]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 21.0.4
   Java vendor: Eclipse Adoptium (https://adoptium.net/)
   Java class version: 65.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.249
   Command line: [-memonce, -de]
   Available memory: 196 MB
   Maximum memory: 28000 MB
   Parallelism: 16
   Language: de
   Date and time: 2024-08-17T21:47:39.117Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
Z:\Imperium\save\Michael\save-2024-08-17-23-47-39-143.xml.gz
java.lang.AssertionError: Unit was not found at location 34, 13

	at hu.openig.mechanics.SimpleWarMovementHandler.removeUnit(SimpleWarMovementHandler.java:244)
	at hu.openig.mechanics.SpaceWarMovementHandler.removeUnit(SpaceWarMovementHandler.java:64)
	at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3993)
	at hu.openig.screen.items.SpacewarScreen$8.invoke(SpacewarScreen.java:3308)
	at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:885)
	at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by Scelletor** [comment]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 21.0.4
   Java vendor: Eclipse Adoptium (https://adoptium.net/)
   Java class version: 65.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.249
   Command line: [-memonce, -de]
   Available memory: 196 MB
   Maximum memory: 28000 MB
   Parallelism: 16
   Language: de
   Date and time: 2024-08-17T21:47:39.117Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
Z:\Imperium\save\Michael\save-2024-08-17-23-47-39-143.xml.gz
java.lang.AssertionError: Unit was not found at location 34, 13

	at hu.openig.mechanics.SimpleWarMovementHandler.removeUnit(SimpleWarMovementHandler.java:244)
	at hu.openig.mechanics.SpaceWarMovementHandler.removeUnit(SpaceWarMovementHandler.java:64)
	at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3993)
	at hu.openig.screen.items.SpacewarScreen$8.invoke(SpacewarScreen.java:3308)
	at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:885)
	at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by akarnokd** [comment]
Hi. Could you also post the file `Z:\Imperium\save\Michael\save-2024-08-17-23-47-39-143.xml.gz` here?

**Comment by Scelletor** [comment]
[save-2024-08-17-23-47-39-143.xml.gz](https://github.com/user-attachments/files/16649469/save-2024-08-17-23-47-39-143.xml.gz)
 Sure here thy

**Comment by hemoridos** [comment]
The exception seems unrelated to the slowness. That's something I'm trying to fix though.
I tried the save you uploaded but so far did not experience slowness.
If you haven't already, you could try a clean install of openIG and/or increasing the Memory in the "Run Settings" of the Launcher.

**Comment by Scelletor** [comment]
If you go into a battle and fire many missiles and then press play and everything explodes it hangs I have already reinstalled it 2x 3x memory I have already set to 28 gb I could also stream it in the discord if you want

**Comment by Scelletor** [comment]
As soon as I restart the game it works for 5 -10 min as soon as I go back into a fan and it gets heavier with the rockets it happens

**Comment by hemoridos** [comment]
Thanks for the info! I think I managed to create something similar though the slowness was only temporary, but it reliably gets me exception above.
I have some ideas what might be the problem. I'll take a look.

**Comment by Scelletor** [comment]
Great thanks to you unfortunately it is permanent until I restart

**Comment by hemoridos** [comment]
Could you try running the game with this jar?
[open-ig.zip](https://github.com/user-attachments/files/16659228/open-ig.zip)
Just extract it to the game's folder.

**Comment by Scelletor** [comment]
Hi, great, looks good, I might ask what the mistake was

**Comment by hemoridos** [comment]
Good to hear!
It was possible to register a fatal explosion animation for a fighter "squad" if multiple fatal shots would hit it in a very short succession.
At the middle of these explosions a unit would get removed from the map, so ideally only one such explosion animation would occur for a unit, but in this case multiple would occur and tried to remove the unit that was already removed/destroyed.
This would happen more often with large rocket salvos dealing a lot of damage in a short period.
