### ISSUE TITLE
Földi csaták után megáll a játékmenet

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1161]
Sziasztok,
A videoproblémát sikerült megoldanom, az OpenGL használatot kellett megtiltani a programnak, így nem vibrál már semmi.
Viszont előjött egy másik probléma.

A földi csaták után a játékmenet megáll, és semmi sem történik mikor már minden katonai célpontot elpusztítottam.
Ilyenkor nyomok egy visszavonulást, és újra megtámadom a bolygót, ekkor azonnal az enyém lesz.

Fordított esetben is előjött már ez a hiba, mikor az én egyik bolygómat támadták meg, ugyanúgy nem folytatódott a játékmenet, csak állt.
Ebben az esetben ki kellett lépnem a játékból teljesen, és újra, és újra végig csinálni, de nem segített.
Frissítettem, újra letöltöttem a Launchert, és a játékot, a Save mappát átpakoltam, azóta ez még nem jelentkezett.
[open-ig.log](https://github.com/user-attachments/files/16735769/open-ig.log)

**Comment by akarnokd** [comment]
Ha megint előjön, kérlek azonnal posztold a legutóbbi mentést és a log fájlt.

A logfájlban két hiba van. Az egyik korrupt telepítésre utal. A másik pedig AI interferenciára utal: épített volna, de közben elfogyott a pénze a döntés és a végrehajtás között.

**Comment by hemoridos** [comment]
Esetleg ha megvan a mentés bolygóval ahol ez előjön akkor arra ránéznék.

Gyanús hogy az erődök számolásánál rontottam el valamit.

**Comment by G-T-T-G** [comment]
Újra sikerült , a Dargslan összes bolygóját támadva, ugyanaz a hiba.
2-3szor is neki kell menni a bolygónak, így 2x-3x 40-45tankot felhasználva, tudom csak elfoglalni, és utána áll.
Mellékeltem az Autosave-et.

![Játékmenet nem folyt](https://github.com/user-attachments/assets/f02aba9f-be33-4be5-97eb-6ebba21ef350)
[save-2024-08-24-16-45-26-754.xml.gz](https://github.com/user-attachments/files/16737011/save-2024-08-24-16-45-26-754.xml.gz)

**Comment by G-T-T-G** [comment]
Ismételten, és most a Java Crash report is feljött.

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_421
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.250
   Command line: []
   Available memory: 1300 MB
   Maximum memory: 3506 MB
   Parallelism: 8
   Language: hu
   Date and time: 2024-08-24T15:57:03.419Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
C:\Users\GTTG\Desktop\OpenIG\save\default\save-2024-08-24-17-57-03-429.xml.gz
java.lang.IllegalArgumentException: Not enough money
	at hu.openig.model.Planet.build(Planet.java:954)
	at hu.openig.mechanics.AutoBuilder.construct(AutoBuilder.java:444)
	at hu.openig.mechanics.DefaultAIControls.actionPlaceBuilding(DefaultAIControls.java:240)
	at hu.openig.mechanics.Planner$20.invoke(Planner.java:1050)
	at hu.openig.mechanics.AI.apply(AI.java:119)
	at hu.openig.screen.CommonResources$20.run(CommonResources.java:726)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


[save-2024-08-24-17-57-03-429.xml.gz](https://github.com/user-attachments/files/16737250/save-2024-08-24-17-57-03-429.xml.gz)

**Comment by akarnokd** [comment]
A crash majd javítva lesz.

@hemoridos 
Úgy néz ki, hogy a győztes ellenőrzésekor a `fortifications` még mindig tartalmazza a megsemmisült laktanyákat, feladás nélkül, emiatt nincs nyertes.

**Comment by hemoridos** [comment]
Az erőd számolást holnap megpróbálom orvosolni, amint gépközelbe kerülök.

**Comment by akarnokd** [comment]
Egy átmeneti javítást tettem a v0.95.251-be, ami után nem sikerült megismételni a beakadást.

Azért @hemoridos nyugodtan ellenőrizheted, hogy tényleg az-e a megoldás.

**Comment by G-T-T-G** [comment]
Sikerült, ez megoldotta úgy fest. Azóta még 15bólygót nyomtam le, semmi para nem volt. THX ! 💯

**Comment by hemoridos** [comment]
@akarnokd Igen ez lesz a megoldás, ezt jól elnéztem.
