### ISSUE TITLE
Bolygó támadás hibajelzés

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1168]
Sziasztok,
Morgath flotta megtámadta az egyik bolygómat, menekülőre fogta, és ekkor bedobta a hibajelzést.
A játék folytatódik gond nélkül.

![image](https://github.com/user-attachments/assets/c479e67e-d50d-4451-9bc8-057e4de4dd57)

[save-2024-08-31-17-43-57-148.xml.gz](https://github.com/user-attachments/files/16825254/save-2024-08-31-17-43-57-148.xml.gz)

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_421
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.252
   Command line: []
   Available memory: 199 MB
   Maximum memory: 3506 MB
   Parallelism: 8
   Language: hu
   Date and time: 2024-08-31T15:43:57.140Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
C:\Users\GTTG\Desktop\OpenIG\save\default\save-2024-08-31-17-43-57-148.xml.gz
java.lang.AssertionError: Unit was not found at location -2, 12

	at hu.openig.mechanics.SimpleWarMovementHandler.removeUnit(SimpleWarMovementHandler.java:244)
	at hu.openig.mechanics.SpaceWarMovementHandler.removeUnit(SpaceWarMovementHandler.java:64)
	at hu.openig.screen.items.SpacewarScreen.removeStructure(SpacewarScreen.java:4999)
	at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3991)
	at hu.openig.screen.items.SpacewarScreen$8.invoke(SpacewarScreen.java:3308)
	at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:885)
	at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

java.lang.AssertionError: Unit was not found at location -2, 19

	at hu.openig.mechanics.SimpleWarMovementHandler.removeUnit(SimpleWarMovementHandler.java:244)
	at hu.openig.mechanics.SpaceWarMovementHandler.removeUnit(SpaceWarMovementHandler.java:64)
	at hu.openig.screen.items.SpacewarScreen.removeStructure(SpacewarScreen.java:4999)
	at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3991)
	at hu.openig.screen.items.SpacewarScreen$8.invoke(SpacewarScreen.java:3308)
	at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:885)
	at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by hemoridos** [comment]
Szia!
Volt utánuk rakéta küldve?

**Comment by G-T-T-G** [comment]
Szia, igen.
