### ISSUE TITLE
Kampányszerkesztő hiba

### ISSUE THREAD

**Issue by G-T-T-G** [akarnokd/open-ig#1172]
Sziasztok,
Nem nagyon működik a kampányszerkesztő. Pár képet beillesztek.
Ez még csak tesztrész lenne?
Köszi GT

![image](https://github.com/user-attachments/assets/31d844a1-98e9-4aac-9597-b5f54336720b)
![image](https://github.com/user-attachments/assets/4d15e118-a2aa-4cc1-863f-565aa0d709c9)
![image](https://github.com/user-attachments/assets/f3735c9a-cd19-4df6-a4f2-9ebc48083bb9)

**Comment by G-T-T-G** [comment]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_421
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.03
   Command line: [-memonce, -hu]
   Available memory: 179 MB
   Maximum memory: 7282 MB
   Parallelism: 8
   Language: en
   Date and time: 2024-09-08T13:03:58.516Z
----
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at hu.openig.utils.U.stacktrace(U.java:615)
	at hu.openig.editors.ce.CEImageRef$1.done(CEImageRef.java:80)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker.doneEDT(Unknown Source)
	at javax.swing.SwingWorker.access$100(Unknown Source)
	at javax.swing.SwingWorker$2.done(Unknown Source)
	at java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
	at java.util.concurrent.FutureTask.cancel(Unknown Source)
	at javax.swing.SwingWorker.cancel(Unknown Source)
	at hu.openig.editors.ce.CEImageRef.setImage(CEImageRef.java:55)
	at hu.openig.editors.ce.CETechnologyImagesPanel.setImages(CETechnologyImagesPanel.java:213)
	at hu.openig.editors.ce.CETechnologyImagesPanel$1.invoke(CETechnologyImagesPanel.java:79)
	at hu.openig.editors.ce.CEValueBox.validateComponent(CEValueBox.java:94)
	at hu.openig.editors.ce.CEBasePanel.setTextAndEnabled(CEBasePanel.java:245)
	at hu.openig.editors.ce.CETechnologyImagesPanel.onMasterChanged(CETechnologyImagesPanel.java:268)
	at hu.openig.editors.ce.CESlavePanel.setMaster(CESlavePanel.java:42)
	at hu.openig.editors.ce.CETechnologyPanel.doDetails(CETechnologyPanel.java:659)
	at hu.openig.editors.ce.CETechnologyPanel$2.valueChanged(CETechnologyPanel.java:155)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by akarnokd** [comment]
Belekezdtem, de sosem fejeztem be. Nem valószínű, hogy valaha kész lesz. Könyebb az XML-eket kézzel szerkesztgetni.

**Comment by G-T-T-G** [comment]
Igen könnyebb, bár ugye az alap mappákat, és a választható kampányok közé való felvitelt jól megcsinálja. (másképp nem is tudom hogyan lehetett volna)
Ami a nagy előnye, hogy a Hajók, és Épületek esetén egy esetleges plusz item hozzáadásához a koordináták vizuálisan sokkal jobbak.
Mostanában nagyon sokat szórakoztam velük :)
