### ISSUE TITLE
Brand new campaign. Error given as soon as second pirate fighter in the first scripted battle died.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#899]
```
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://code.google.com/p/open-ig/issues/list
Please include the following diagnostic information followed by the error 
stacktrace(s):
   Java version: 1.7.0_21
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows XP, x86, 5.1
   Game version: 0.95.198
   Command line: [-memonce, -en]
   Available memory: 146 MB
   Maximum memory: 804 MB
   Parallelism: 2
   Language: en
   Date and time: 2014-11-04T18:29:17.445Z
----
A crash save may have been created. Please attach it in the issue report 
(zipped).
C:\Program Files\Imperium\save\default\save-2014-11-04-18-29-17-445.xml.gz
java.lang.AssertionError: Fleet 1255 has no previous planet to return to!
    at hu.openig.mechanics.AITrader.returnToPreviousPlanet(AITrader.java:613)
    at hu.openig.mechanics.AITrader$AITraderSpaceBattle.spaceBattleDone(AITrader.java:598)
    at hu.openig.screen.items.SpacewarScreen.concludeBattle(SpacewarScreen.java:4416)
    at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3760)
    at hu.openig.screen.items.SpacewarScreen$8.invoke(SpacewarScreen.java:3012)
    at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:869)
    at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:245)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)


```

Original issue reported on code.google.com by `Jonathan...@gmail.com` on 4 Nov 2014 at 6:32

Attachments:
- [save-2014-11-04-18-32-21-039.xml.gz](https://storage.googleapis.com/google-code-attachments/open-ig/issue-899/comment-0/save-2014-11-04-18-32-21-039.xml.gz)

**Comment by akarnokd** [comment]
Haven't encountered this ever since.
