### ISSUE TITLE
Campaign. Tried to load game. Received error. Can only load crash save.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akarnokd/open-ig#902]
```
   Java version: 1.7.0_21
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows XP, x86, 5.1
   Game version: 0.95.200
   Command line: [-memonce, -en]
   Available memory: 295 MB
   Maximum memory: 804 MB
   Parallelism: 2
   Language: en
   Date and time: 2014-11-07T22:46:43.750Z
----
A crash save may have been created. Please attach it in the issue report 
(zipped).
C:\Program Files\Imperium\save\default\save-2014-11-07-22-46-43-765.xml.gz
java.lang.AssertionError: DiplomaticRelation.first unknown: <relation 
first='Pirates2' second='Pirates' full='true' trade-agreement='false' 
strong-alliance='false' wont-talk='true' 
last-contact='3427-08-18T01:50:00.000Z' value='29.0' ally-against=''/>

    at hu.openig.model.World.loadDiplomaticRelations(World.java:2893)
    at hu.openig.model.World.loadState(World.java:1542)
    at hu.openig.GameWindow.loadWorldData(GameWindow.java:2322)
    at hu.openig.GameWindow$13.run(GameWindow.java:1557)
    at java.lang.Thread.run(Unknown Source)
```

Original issue reported on code.google.com by `Jonathan...@gmail.com` on 7 Nov 2014 at 10:51

Attachments:
- [save-2014-11-07-22-37-46-703.xml.gz](https://storage.googleapis.com/google-code-attachments/open-ig/issue-902/comment-0/save-2014-11-07-22-37-46-703.xml.gz)

**Comment by sashakozod** [comment]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_111
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 7, x86, 6.1
   Game version: 0.45
   Command line: [-verify]
   Available memory: 4 MB
   Maximum memory: 247 MB
   Parallelism: 4
   Language: ru
   Date and time: 2016-10-23T20:40:17.547Z
----
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.MeteredStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at hu.openig.launcher.Launcher.downloadFiles(Launcher.java:2093)
	at hu.openig.launcher.Launcher$40.doInBackground(Launcher.java:1954)
	at hu.openig.launcher.Launcher$40.doInBackground(Launcher.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at hu.openig.launcher.Launcher$40.done(Launcher.java:1969)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.SSLSocketImpl.checkEOF(Unknown Source)
	at sun.security.ssl.AppInputStream.available(Unknown Source)
	at java.io.BufferedInputStream.available(Unknown Source)
	at sun.net.www.MeteredStream.available(Unknown Source)
	at sun.net.www.http.KeepAliveStream.close(Unknown Source)
	at java.io.FilterInputStream.close(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(Unknown Source)
	at hu.openig.launcher.Launcher.downloadFiles(Launcher.java:2135)
	at hu.openig.launcher.Launcher$40.doInBackground(Launcher.java:1954)
	at hu.openig.launcher.Launcher$40.doInBackground(Launcher.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: javax.net.ssl.SSLException: java.net.SocketException: Connection reset
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.MeteredStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at hu.openig.launcher.Launcher.downloadFiles(Launcher.java:2093)
	... 8 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	... 16 more
