### ISSUE TITLE
Errorok özöne indulásnál

### ISSUE THREAD

**Issue by feqolosi** [akarnokd/open-ig#918]
Elindítom a játékot, rányomok egy gombra, bármit csinálok, feljön egy ablak és közli, hogy:

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.7.0_75
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Linux, amd64, 3.16.0-4-amd64
   Game version: 0.95.204
   Command line: [-memonce, -hu]
   Available memory: 43 MB
   Maximum memory: 739 MB
   Parallelism: 4
   Language: hu
   Date and time: 2015-03-19T13:44:26.266Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
javax.sound.sampled.LineUnavailableException
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
	at hu.openig.sound.Sounds.addLine(Sounds.java:174)
	at hu.openig.sound.Sounds.getLine(Sounds.java:189)
	at hu.openig.sound.Sounds.playSound(Sounds.java:258)
	at hu.openig.sound.Sounds.playSound(Sounds.java:237)
	at hu.openig.screen.CommonResources.playSound(CommonResources.java:1063)
	at hu.openig.screen.ScreenBase.buttonSound(ScreenBase.java:289)
	at hu.openig.screen.items.MainScreen$8.invoke(MainScreen.java:426)
	at hu.openig.screen.items.MainScreen$ClickLabel.mouse(MainScreen.java:142)
	at hu.openig.ui.UIContainer.mouse(UIContainer.java:112)
	at hu.openig.screen.ScreenBase.mouse(ScreenBase.java:108)
	at hu.openig.screen.items.MainScreen.mouse(MainScreen.java:307)
	at hu.openig.GameWindow$MouseActions.invoke(GameWindow.java:1131)
	at hu.openig.GameWindow$MouseActions.mouseReleased(GameWindow.java:1162)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:713)
	at java.awt.EventQueue$4.run(EventQueue.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Ja és hang sincs...

**Comment by akarnokd** [comment]
Sajnos ez elég gyakori Linux hiba. Próbálkozz meg a [ezekkel az opciókkal](https://github.com/akarnokd/open-ig/wiki/Troubleshooting).

**Comment by feqolosi** [comment]
Köszönöm a tippet, mihelyst átállítottam ALSA-ra a JAVA audio backendet, máris működik minden!
A "gyakori Linux hiba" kitételt én eléggé erősnek érzem, ez nem Linux hiba, ez a PulseAudio hibája! Ha a Linux lenne hibás, akkor sehogy se menne...
