### ISSUE TITLE
Failed to remove building 17581 (PlasmaProjector on Garthog 4)

### ISSUE THREAD

**Issue by anonymissimus** [akarnokd/open-ig#920]
Attached manual save (save-2015-03-23-22-08-56-687.xml.gz) is from just before.

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.7.0_04
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows XP, x86, 5.1
   Game version: 0.95.204
   Command line: [-memonce, -en]
   Available memory: 110 MB
   Maximum memory: 804 MB
   Parallelism: 2
   Language: en
   Date and time: 2015-03-23T21:08:59.406Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
I:\programs\open_imp_gal\save\default\save-2015-03-23-22-08-59-421.xml.gz
java.lang.IllegalStateException: Failed to remove building 17581 (PlasmaProjector on Garthog 4)
	at hu.openig.model.Planet.demolish(Planet.java:1198)
	at hu.openig.mechanics.DefaultAIControls.actionDemolishBuilding(DefaultAIControls.java:241)
	at hu.openig.mechanics.ColonyPlanner$5.invoke(ColonyPlanner.java:242)
	at hu.openig.mechanics.AI.apply(AI.java:119)
	at hu.openig.screen.CommonResources$20.run(CommonResources.java:730)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:701)
	at java.awt.EventQueue.access$000(EventQueue.java:102)
	at java.awt.EventQueue$3.run(EventQueue.java:662)
	at java.awt.EventQueue$3.run(EventQueue.java:660)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:671)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

**Comment by anonymissimus** [comment]
Can't manage to attach stuff...saves: https://www.mediafire.com/?3qnc8fqyacg9g9l

**Comment by akarnokd** [comment]
Thanks. It's nothing major but only an AI state oversight: attempting to demolish a building twice.

**Comment by akarnokd** [comment]
Thanks. Fixed in https://github.com/akarnokd/open-ig/commit/b3e9f277562f4a7da278704e2ddd15bb417829b6 .
