### ISSUE TITLE
Saved game (on version 0.95.204) loading fail after update

### ISSUE THREAD

**Issue by leventelas** [akarnokd/open-ig#923]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.7.0_75
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Linux, amd64, 3.19.2-1-ARCH
   Game version: 0.95.205
   Command line: [-memonce, -hu]
   Available memory: 215 MB
   Maximum memory: 739 MB
   Parallelism: 4
   Language: hu
   Date and time: 2015-03-25T23:15:38.950Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
java.lang.NoSuchMethodError: java.lang.Double.isFinite(D)Z
	at hu.openig.model.Planet.morale(Planet.java:1567)
	at hu.openig.model.World.processPlanets(World.java:710)
	at hu.openig.model.World.loadCampaign(World.java:357)
	at hu.openig.GameWindow.loadWorldData(GameWindow.java:2318)
	at hu.openig.GameWindow$13.run(GameWindow.java:1557)
	at java.lang.Thread.run(Thread.java:745)

Where can I find the crash saved zip file?

**Comment by leventelas** [comment]
I tried to start a new game:

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.7.0_75
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Linux, amd64, 3.19.2-1-ARCH
   Game version: 0.95.205
   Command line: [-memonce, -hu]
   Available memory: 216 MB
   Maximum memory: 739 MB
   Parallelism: 4
   Language: hu
   Date and time: 2015-03-25T23:36:20.464Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
java.lang.NoSuchMethodError: java.lang.Double.isFinite(D)Z
	at hu.openig.model.Planet.morale(Planet.java:1567)
	at hu.openig.model.World.processPlanets(World.java:710)
	at hu.openig.model.World.loadCampaign(World.java:357)
	at hu.openig.GameWindow.loadWorldData(GameWindow.java:2318)
	at hu.openig.GameWindow$13.run(GameWindow.java:1557)
	at java.lang.Thread.run(Thread.java:745)

java.lang.NoSuchMethodError: java.lang.Double.isFinite(D)Z
	at hu.openig.model.Planet.morale(Planet.java:1567)
	at hu.openig.model.World.processPlanets(World.java:710)
	at hu.openig.model.World.loadCampaign(World.java:357)
	at hu.openig.GameWindow.loadWorldData(GameWindow.java:2318)
	at hu.openig.GameWindow$13.run(GameWindow.java:1557)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "Start Game Loading" java.lang.NoSuchMethodError: java.lang.Double.isFinite(D)Z
	at hu.openig.model.Planet.morale(Planet.java:1567)
	at hu.openig.model.World.processPlanets(World.java:710)
	at hu.openig.model.World.loadCampaign(World.java:357)
	at hu.openig.screen.items.SingleplayerScreen$7.run(SingleplayerScreen.java:241)

**Comment by akarnokd** [comment]
Can you switch to Java 8 temporarily?

**Comment by akarnokd** [comment]
Thanks. Fixed in a hot patch. If it doesn't get applied, click on the Other options button in the Launcher and chose verify installation.
