### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by anonymissimus** [akarnokd/open-ig#940]
I didn't do something in particular to cause this I think (stack trace points to ai anyway):
crashsave reproduces: https://www.mediafire.com/?1754si624ba264b

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.7.0_04
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 51.0
   Operating system: Windows XP, x86, 5.1
   Game version: 0.95.205
   Command line: [-memonce, -en]
   Available memory: 253 MB
   Maximum memory: 804 MB
   Parallelism: 2
   Language: en
   Date and time: 2015-03-27T21:19:06.234Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
I:\programs\open_imp_gal\save\default\save-2015-03-27-22-19-06-265.xml.gz
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
	at java.util.ArrayList$Itr.next(ArrayList.java:791)
	at hu.openig.mechanics.ResearchPlanner.demolishOneLabIf(ResearchPlanner.java:212)
	at hu.openig.mechanics.ResearchPlanner.demolishOneLabFor(ResearchPlanner.java:196)
	at hu.openig.mechanics.ResearchPlanner.planReconstruction(ResearchPlanner.java:168)
	at hu.openig.mechanics.ResearchPlanner.plan(ResearchPlanner.java:118)
	at hu.openig.mechanics.Planner.run(Planner.java:217)
	at hu.openig.mechanics.AI.manage(AI.java:544)
	at hu.openig.screen.CommonResources.runAIAsync(CommonResources.java:713)
	at hu.openig.screen.CommonResources$19.run(CommonResources.java:683)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)

**Comment by akarnokd** [comment]
I've released a hotfix (same version number). The crash should go away.
