### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by MajorBlack** [akarnokd/open-ig#960]
First of all, I would like to admit that Open Imperium Galactica is a remarkable project that helps us to play the great game on modern hardware. Thank you for your great work!
Unfortunately, when playing the following error occurs:

An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_66
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 10, amd64, 10.0
   Game version: 0.95.205
   Command line: [-memonce, -en]
   Available memory: 14 MB
   Maximum memory: 740 MB
   Parallelism: 8
   Language: en
   Date and time: 2016-01-17T05:50:41.177Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at hu.openig.screen.TechnologyVideoRenderer.prepare(TechnologyVideoRenderer.java:126)
	at hu.openig.screen.TechnologyVideoRenderer$1.run(TechnologyVideoRenderer.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.lang.OutOfMemoryError: Java heap space
	at java.util.LinkedHashMap.newNode(Unknown Source)
	at java.util.HashMap.putVal(Unknown Source)
	at java.util.HashMap.put(Unknown Source)
	at hu.openig.utils.XElement.set(XElement.java:561)
	at hu.openig.model.World.saveState(World.java:1337)
	at hu.openig.GameWindow.saveWorld(GameWindow.java:1285)
	at hu.openig.Startup$2.invoke(Startup.java:87)
	at hu.openig.Startup$2.invoke(Startup.java:1)
	at hu.openig.utils.ConsoleWatcher$5.crashSave(ConsoleWatcher.java:221)
	at hu.openig.utils.ConsoleWatcher$5.run(ConsoleWatcher.java:207)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Music continues with interruptions, but the game screen is not responding.
I hope this my report may help in further game development. Thank you!

**Comment by MajorBlack** [comment]
Here are 2 saves, maybe it will be useful.

[Saves.zip](https://github.com/akarnokd/open-ig/files/93230/Saves.zip)

**Comment by akarnokd** [comment]
Hi and thanks for reporting.

Are you playing in a large skirmish map? You can increase the memory in the launcher in the runtime settings to 1024 MB.

**Comment by MajorBlack** [comment]
Hi! I'm playing standard campaign. I have tried to set runtime memory settings in the launcher to 1024 MB and it seems that it helps!
Thank you!

**Comment by akarnokd** [comment]
Could you upload your save file again?

**Comment by MajorBlack** [comment]
Here it is my last save. I have started new game and played a little.
[save-2016-01-20-19-30-06-706.xml.gz](https://github.com/akarnokd/open-ig/files/97716/save-2016-01-20-19-30-06-706.xml.gz)
I guess that my problem could occur due to the changes in "textCacheSize" parameter in open-ig-config.xml file. But now everything seems working fine. Please, see attached config files (open-ig-config.xml and open-ig-launcher-config.xml) if it is useful:
[configs.zip](https://github.com/akarnokd/open-ig/files/97733/configs.zip)
Sorry for inconvenience and thank you for your great work!
