### ISSUE TITLE
Error in space combat end

### ISSUE THREAD

**Issue by hdstealth** [akarnokd/open-ig#987]
An unexpected error occurred.
You should consider submitting an error report via the project issue list:
https://github.com/akarnokd/open-ig/issues
Please include the following diagnostic information followed by the error stacktrace(s):
   Java version: 1.8.0_40
   Java vendor: Oracle Corporation (http://java.oracle.com/)
   Java class version: 52.0
   Operating system: Windows 7, x86, 6.1
   Game version: 0.95.209
[save-2016-07-18-21-18-51-189.xml.gz](https://github.com/akarnokd/open-ig/files/370108/save-2016-07-18-21-18-51-189.xml.gz)

   Command line: [-memonce, -ru, -noclickskip]
   Available memory: 213 MB
   Maximum memory: 804 MB
   Parallelism: 2
   Language: ru
   Date and time: 2016-07-18T18:18:51.169Z
----
A crash save may have been created. Please attach it in the issue report (zipped).
E:\games\IG\save\stas\save-2016-07-18-21-18-51-189.xml.gz
java.util.UnknownFormatConversionException: Conversion = ' '
	at java.util.Formatter.checkText(Unknown Source)
	at java.util.Formatter.parse(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at hu.openig.model.Labels.format(Labels.java:82)
	at hu.openig.scripting.missions.Mission.format(Mission.java:183)
	at hu.openig.scripting.missions.Mission2.spacewarFinishTraderVsPirate(Mission2.java:277)
	at hu.openig.scripting.missions.Mission2.onSpacewarFinish(Mission2.java:250)
	at hu.openig.scripting.MainCampaignScripting.onSpacewarFinish(MainCampaignScripting.java:905)
	at hu.openig.screen.items.SpacewarScreen.concludeBattle(SpacewarScreen.java:4197)
	at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3540)
	at hu.openig.screen.items.SpacewarScreen$7.invoke(SpacewarScreen.java:2774)
	at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:866)
	at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

java.util.UnknownFormatConversionException: Conversion = ' '
	at java.util.Formatter.checkText(Unknown Source)
	at java.util.Formatter.parse(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at hu.openig.model.Labels.format(Labels.java:82)
	at hu.openig.scripting.missions.Mission.format(Mission.java:183)
	at hu.openig.scripting.missions.Mission7.spacewarFinishTraderVsPirate(Mission7.java:270)
	at hu.openig.scripting.missions.Mission7.onSpacewarFinish(Mission7.java:322)
	at hu.openig.scripting.MainCampaignScripting.onSpacewarFinish(MainCampaignScripting.java:905)
	at hu.openig.screen.items.SpacewarScreen.concludeBattle(SpacewarScreen.java:4197)
	at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3540)
	at hu.openig.screen.items.SpacewarScreen$7.invoke(SpacewarScreen.java:2774)
	at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:866)
	at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

java.util.UnknownFormatConversionException: Conversion = ' '
	at java.util.Formatter.checkText(Unknown Source)
	at java.util.Formatter.parse(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.util.Formatter.format(Unknown Source)
	at java.lang.String.format(Unknown Source)
	at hu.openig.model.Labels.format(Labels.java:82)
	at hu.openig.scripting.missions.Mission.format(Mission.java:183)
	at hu.openig.scripting.missions.Mission7.spacewarFinishTraderVsPirate(Mission7.java:270)
	at hu.openig.scripting.missions.Mission7.onSpacewarFinish(Mission7.java:322)
	at hu.openig.scripting.MainCampaignScripting.onSpacewarFinish(MainCampaignScripting.java:905)
	at hu.openig.screen.items.SpacewarScreen.concludeBattle(SpacewarScreen.java:4197)
	at hu.openig.screen.items.SpacewarScreen.doSpacewarSimulation(SpacewarScreen.java:3540)
	at hu.openig.screen.items.SpacewarScreen$7.invoke(SpacewarScreen.java:2774)
	at hu.openig.screen.CommonResources.doTimerTick(CommonResources.java:866)
	at hu.openig.screen.CommonResources$1.actionPerformed(CommonResources.java:247)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by akarnokd** [comment]
Thanks, likely some missing russian labels. I'll ckeck them tomorrow.

**Comment by akarnokd** [comment]
Fixed via https://github.com/akarnokd/open-ig/commit/c674e34c28384552402bb0abf8d986f43668e87a
